### ISSUE TITLE
Reiter Meta Daten verbessern

### ISSUE THREAD

**Issue by einfachMel** [fhac-ewi/grid-optimizer#117]
- [x]  hilfreich wäre ein Text was gemacht werden muss (sowas von "bitte alle Metadaten mit Werten füllen") oder nur die die Pflicht sind
- [x] Buttons zum hoch- & herunterladen der json-Dateien sind im Weg mit dem bestätigen-Button -> können weg
- [x] der Reiter ist nicht flexibel an die Fenstergröße bzw. Bildschirmgröße (es gibt keinen Scrollbalken oder kleinere Skalierung). Man sieht nicht alles und hat auch keinen Weg dahin zu kommen
